language: generic
sudo: required
services:
  - docker

before_install:
  - docker build  -t pravinchikhale/frontend -f Dockerfile.dev .
  - echo "Hello Wify, good morning!"

script:
  - docker run -e CI=true pravinchikhale/frontend npm run test

## Commenting configuration
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "docker-frontend"
#  env: "DockerFrontend-env"
#  bucket_name: "elasticbeanstalk-us-east-1-496506661305"
#  bucket_path: "docker-frontend"
#  on:
#    branch: master
#  access_key_id:  $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
